apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: "mmdsmart.com"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  selector:
    app: redis-cluster
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP


# gcloud compute firewall-rules create -tbd-redis-cluster --allow=tcp:6379




